# Array creation

In [2]:
import numpy as np

In [3]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array[3])

numpy.float64

In [5]:
test_array = np.array([1,4,5,'8'], float)
print(test_array)
print(type(test_array[3]))
print(test_array.dtype)  # dtype -> numpy array의 데이터 type을 반환함
print(test_array.shape)  #shape -> numpy array의 object의 dimension 구성을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [7]:
test_array = np.array([1,4,5,"8"],float) #String Type의 데이터를 입력해도...
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array[3]) # Float Type으로 자동 형변환 실시

numpy.float64

In [10]:
test_array.dtype  # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [11]:
test_array.shape  # Array(배열) 의 shape을 반환함

(4,)

# Array shape (martix)

In [20]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

# Array shape (3rd order tensor)

In [23]:
tensor = [[[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
          [[1,2,5,8], [1,2,5,8], [1,2,5,8]]]
           

np.array(tensor, int).shape

(4, 3, 4)

In [24]:
np.array(tensor, int).ndim

3

In [25]:
np.array(tensor, int).size

48

# Array dtype

- Ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정됨

In [26]:
np.array([[1,2,3],[4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.array([[1,2,3],[4.5,'5','6']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [ ]:
# nbytes - ndarray object의 메모리 크기를 반환함

In [28]:
np.array([[1,2,3], [4.5,'5','6']], dtype=np.float32).nbytes
# 32bits = 4bites -> 6 * 4 bytes

24

In [29]:
np.array([[1,2,3], [4.5,'5','6']], dtype=np.int8).nbytes
# 8bits = 1bytes -> 6 * 1bytes

6

In [31]:
np.array([[1,2,3], [4.5,'5','6']], dtype=np.int64).nbytes
# 64bits = 8bytes -> 6 * 8bytes

48

# Handling shape

reshape : Array의 shape의 크기를 변경함 (element의 갯수는 동일)
          , Array의 size만 같아면 다차원으로 자유로이 변형가능

In [3]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [6]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [5]:
np.array(test_matrix).reshape(8, ).shape

(8,)

In [7]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(-1, 2).shape  # -1 : size를 기반으로row 개수 선정

(4, 2)

(1) reshape(-1, 정수) 의 행(row) 위치에 '-1'이 들어있을 경우

In [9]:
import numpy as np

In [15]:
x = np.arange(12).reshape(3, 4)

In [16]:
x.shape

(3, 4)

In [17]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
x.reshape(-1, 1)  # x.reshape(-1, 1) => shape(12, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [19]:
x.reshape(-1, 2)  # x.reshape(-1, 1) => shape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
x.reshape(-1, 3)  # x.reshape(-1, 3) => shape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
x.reshape(-1, 4) # x.reshape(-1, 4) => shape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

(2) reshape(정수, -1) 의 열(column) 위치에 '-1'이 들어있을 경우

In [22]:
x.reshape(1, -1) # x.reshape(1, -1) => shape(1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [23]:
x.reshape(2, -1) # x.reshape(2, -1) => shape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
x.reshape(3, -1) # x.reshape(3, -1) => shape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
x.reshape(4, -1) # x.reshape(4, -1) => shape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
x.reshape(-1) # x.reshape(1, -1)과 같이 일차원 배열을 반환한다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
x.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

flatten : 다차원 array를 1차원 array로 변환

In [28]:
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# Indexing & slicing

Indexing
  - List와 달리 이차원 배열에서 [0,0] 과 같이 표기법을 제공함
  - Matrix 일 경우 앞은 row, 뒤는 column을 의미함 

In [34]:
a = np.array([[1,2,3], [4.5,5,6]], int)
print(a)
print(a[0,0])   # Two dimensional array representation #1
print(a[0][0])  # Two dimensional array representation #2

a[0,0] = 12     # Matrix 0,0 에 12 할당
print(a)

a[0][0] = 5     # Matrix 0,0 에 5 할당
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[5 2 3]
 [4 5 6]]


In [37]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
test_example[0][0]

1

In [39]:
test_example[0,0]

1

In [41]:
test_example[0,0] = 12 # Matrix 0,0 에 12 할당
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [42]:
test_example[0][0] = 5  # Matrix 0,0 에 5 할당
test_example[0, 0]

5

In [46]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a[:,2:] # 전체 Row의 2열 이상
a[1,1:3] # 1 Row의 1열 ~ 2열
a[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [47]:
test_example = np.array([
    [1, 2, 5, 8], [1, 2, 5, 8], [1,2, 5, 8], [1, 2, 5, 8]], int)
test_example[:2, :]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [50]:
test_example = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
test_example[:, 2:] #전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [52]:
test_example[1, 1:3]  # 1 Row의 1열 ~ 2열

array([7, 8])

In [53]:
test_example[1:3]  # 1 Row ~ 2 Row의 전체

array([[ 6,  7,  8,  9, 10]])

# creation function

In [55]:
import numpy as np

In [57]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
np.arange(0, 5, 0.5)  # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [61]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# ones, zeros and empty

- zeros - 0으로 가득한 ndarray 생성
- np.zeros(shape, dtype, order)

In [62]:
np.zeros(shape=(10,), dtype=np.int8)   # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [64]:
np.zeros((2,5))    # 2 by 5 - zero matrix 생성 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- ones - 1로 가득한 ndarrary 생성
- np.ones(shape, dtype, order)

In [65]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [66]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- empty - shape만 주어지고 비어있는 ndarray 생성
          (memory initialization 이 되지 않음)

In [71]:
np.empty(shape=(10,), dtype=np.int8)

array([ 112,  -34, -101,  -60,  -39,    1,    0,    0,    0,    0],
      dtype=int8)

In [72]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# something_like

- 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환

In [73]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# identity

- 단위 행렬(i 행렬)을 생성함

In [74]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [75]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye

- 대각선인 1 인 행렬, k값의 시작 index의 변경이 가능

In [76]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.eye(3,5,k=2)  # k => start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# diag

- 대각 행렬의 값을 추출함

In [80]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [81]:
np.diag(matrix, k=1)  # k -> start index

array([1, 5])

# random sampling

In [82]:
np.random.uniform(0,1,10).reshape(2,5)  # 균등분포

array([[0.23736599, 0.71434555, 0.13060837, 0.00880033, 0.67783727],
       [0.55450099, 0.07704784, 0.54416137, 0.7690508 , 0.62101482]])

In [83]:
np.random.normal(0,1,10).reshape(2,5)  #정규분포

array([[ 9.64075579e-01, -1.59857501e-01,  4.37697156e-04,
         1.06441794e+00,  9.05543501e-01],
       [ 1.75106532e+00, -1.80222612e+00, -8.25015076e-01,
        -4.96893560e-01, -1.68645881e+00]])

# sum

- ndarray 의 element 들 간의 합을 구함, list의 sum 기능과 동일

In [84]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
test_array.sum(dtype=np.float)

C:\Users\BAEKJI~1\AppData\Local\Temp/ipykernel_16244/3740136754.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_array.sum(dtype=np.float)


55.0

# axis

- 모든 operation function 을 실행할 때,기준이 되는 dimension 축

In [88]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [90]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [91]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [92]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [93]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

# mean & std

 - ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [94]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [97]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

# Mathematical functions

In [98]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

# concatenate

- Numpy array 를 합치는 함수

In [99]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [100]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [102]:
a = np.arra = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.concatenate( (a,b) , axis=0)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [103]:
a = np.array([ [1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate( (a,b.T) , axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# Array operations

Operations b/t arrays
- Numpy는 array간의 기본적인 사칙 연산을 지원함

In [3]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [4]:
test_a + test_a # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [5]:
test_a - test_a  # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

element-wise operations
- Array간 shape이 같을 때 일어나는 연산

In [8]:
matrix_a = np.arange(1, 13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# Dot product

- Matrix의 기본 연산
- dot 함수 사용

In [9]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7, 13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

# Transpose

- transpose 또는 T attribute 사용

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

# broadcasting

    - Shape 이 다른 배열 간 연산을 지원하는 기능

    - Scalar-vector 외에도 vector-matrix 간의 연산도 지원

In [3]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [4]:
test_matrix + scalar # Matrix + Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [6]:
test_matrix - scalar # Matrix - Scalar 덧셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [7]:
test_matrix * 5 # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [8]:
test_matrix / 5 # Matrix - Scalar 나눗셈

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [9]:
test_matrix // 0.2  # Matrix - Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [10]:
test_matrix ** 2 # Matrix - Scalar 제곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [12]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

# Numpy performance #1

In [13]:
def sclar vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 10000000

vector = list(range(iternation_max))
sclar = 2

%timeit scalr vector product(scalar, vector)  # for loop을 이용한 성능
%timeit [sclar * value for value in range(iternation_max)]  #list comprhension을 ㅣ이용한 성능
%timeit np.arange(iternation_max) * scalar  # numpy를 이용한 성능

SyntaxError: invalid syntax (Temp/ipykernel_19836/1151484978.py, line 1)

In [14]:
def sclar_vector_product(scalar, vector):
 result = []
 for value in vector:
 result.append(scalar * value)
 return result 
iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2
%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

IndentationError: expected an indented block (Temp/ipykernel_19836/2435834398.py, line 4)

# comparisons

# All & Any

- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.any(a>5), np.any(a<0)  # any -> 하나라도 조건에 만족한다면 true

(True, False)

In [18]:
np.all(a>5), np.all(a<10)  # all -> 모두가 조건에 만족한다면 true

(False, True)

# Comparison operation #1

- Numpy는 배열의 크기가 동일 할 때 element간 비교의 결과를 Boolean type으로 반환하여 돌려줌

In [19]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [20]:
test_a == test_b

array([False, False, False])

In [22]:
(test_a > test_b).any()  # any -> 하나리도 true라면 true

True

# Comparison operation #2

In [23]:
a = np.array([1, 3, 0], float)
np.logical_and(a>0, a<3) # and 조건의 condition

array([ True, False, False])

In [24]:
b = np.array([True, False, True], bool)
np.logical_not(b)  # NOT 조건의 condition

array([False,  True, False])

In [25]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

# np.where

In [26]:
np.where(a > 0, 3, 2) # where(condition, True, FALSE)

array([3, 3, 2])

In [27]:
a = np.arange(10)
np.where(a>5)  # Index 값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [29]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)  # Nor a Number

array([False,  True, False])

In [30]:
np.isfinite(a) 

array([ True, False, False])

# argmax & argmin

- array내 최대값 또는 최소값의 index를 반환함

In [4]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

- axis 기반의 반환

In [5]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

# boolean & fancy index

boolean index  
- numpy는 배열의 특정 조건에 따른 값을 배열 형태로 추출할 수 있음.
- Comparison operation 함수들도 모두 사용 가능

In [6]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [8]:
test_array[test_array > 3]   # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [10]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

fancy index
- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [11]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)  # 반드시 integer로 선언
a[b]  #bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [12]:
a.take(b)  # take 함수 : bracket index 와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [13]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]  # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])